const targets=await (await fetch("http://127.0.0.1:9233/json")).json();
const page=targets.find(x=>x.type==="page"&&x.url.includes("127.0.0.1:8910"));if(!page)throw new Error("page target not found");
const ws=new WebSocket(page.webSocketDebuggerUrl);let seq=0;const pending=new Map(),exceptions=[];await new Promise((res,rej)=>{ws.onopen=res;ws.onerror=rej});
ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result)}if(m.method==="Runtime.exceptionThrown")exceptions.push(m.params.exceptionDetails.text)};
function call(method,params={}){return new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}))})}
async function ev(expression){const r=await call("Runtime.evaluate",{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.text);return r.result.value}
await call("Runtime.enable");await call("Page.enable");await call("Page.reload",{ignoreCache:true});await new Promise(r=>setTimeout(r,1800));
for(let n=0;n<30;n++){if(await ev("!!document.getElementById('criticism')&&!!document.getElementById('newsroom')&&typeof magazineV2==='function'"))break;await new Promise(r=>setTimeout(r,300))}await call("Emulation.setDeviceMetricsOverride",{width:390,height:844,deviceScaleFactor:1,mobile:true});await new Promise(r=>setTimeout(r,350));
const out={};out.order=await ev("[...document.querySelectorAll('main > section')].map(x=>x.id).filter(Boolean)");out.discoverIndex=out.order.indexOf("discover");out.criticismIndex=out.order.indexOf("criticism");out.newsIndex=out.order.indexOf("newsroom");
out.colors=await ev("({body:getComputedStyle(document.body).backgroundColor,crit:getComputedStyle(document.getElementById('criticism')).backgroundColor,news:getComputedStyle(document.getElementById('newsroom')).backgroundColor,accent:getComputedStyle(document.documentElement).getPropertyValue('--lime').trim()})");out.brandMotif=await ev("({bar:getComputedStyle(document.querySelector('.topbar .nav'),'::after').backgroundColor,width:getComputedStyle(document.querySelector('.topbar .nav'),'::after').width,mark:getComputedStyle(document.querySelector('.mark'),'::before').backgroundColor})");
out.mobileCrit=await ev("!!document.querySelector('.mobile-nav [data-scroll=criticism]')");out.fullCrits=await ev("magazineV2().filter(isMagazineLongformV2).length");await ev("openMagazineAnnualV2();true");await new Promise(r=>setTimeout(r,250));out.koreanSerif=await ev("({font:getComputedStyle(document.querySelector('.annual-copy')).fontFamily,line:getComputedStyle(document.querySelector('.annual-copy')).lineHeight})");await ev("closePanelV08(document.getElementById('magAnnualV2'));true");
await ev("openSharePanelV05(Object.keys(MOVIES)[0]);true");await new Promise(r=>setTimeout(r,250));out.sharePresets=await ev("[...document.querySelectorAll('#presetRow [data-preset]')].map(x=>({k:x.dataset.preset,n:x.textContent,on:x.classList.contains('on')}))");out.shareBlob=await ev("(async()=>{const b=await makeShareBlobV05(activeMovieCode,readV05Opts());return b.size})()");
await ev("openMagazineStudioV2(magazineV2().find(isMagazineLongformV2).id);enableCardManualV2();true");await new Promise(r=>setTimeout(r,300));out.cardRoles=await ev("[...document.querySelectorAll('[data-card-role]')].map(x=>x.value)");out.roleClasses=await ev("[...document.querySelectorAll('.cardnews-thumbs article')].map(x=>[...x.classList].find(c=>c.startsWith('role-')))");out.cardRoleBlob=await ev("(async()=>{const i=studioItemFromForm(),s=cardSlideDataV2(i);return (await makeCardSlideBlobV2(i,s[s.length-1],s.length-1)).size})()");
await call("Emulation.setDeviceMetricsOverride",{width:1440,height:1100,deviceScaleFactor:1,mobile:false});await new Promise(r=>setTimeout(r,250));out.desktop=await ev("({posterCols:getComputedStyle(document.getElementById('posterGrid')).gridTemplateColumns,newsCols:getComputedStyle(document.querySelector('.news-grid')).gridTemplateColumns})");out.exceptions=exceptions;console.log(JSON.stringify(out,null,2));ws.close();
